### ISSUE TITLE
Missing dots on Cyrillic letters

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1051]
### Font 
NotoSans-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
Date: 2018-02-24

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The soft-dotted Cyrillic letters U+0456 and U+0458 are missing their dots, except when the language is set to Serbian.

### Character data
іј
U+0456 CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
U+0458 CYRILLIC SMALL LETTER JE

### Screenshot
![іј](https://user-images.githubusercontent.com/1124347/36633486-a75518a6-1964-11e8-8066-98e986564b60.png)

**Comment by SerjCh** [comment]
Hi, in [this version 2012 of Noto Sans](https://fonts.google.com/specimen/Noto+Sans) all fine with dots, the side question is - where is possible to get 2012 Noto Sans Thin?

**Comment by dscorbett** [comment]
This bug also appears in Noto Serif and Noto Sans Mono.

**Comment by Mystic-Mirage** [comment]
I've just opened TTF file with Fontforge -- Cyrillic **_і_** has the dot above. Technically Cyrillic glyph is just a reference to Latin **_i_**. But it isn't shown properly for some reason.

**Comment by aleslavista** [comment]
I can confirm this bug still exists on Lubuntu 18.10

**Comment by Mystic-Mirage** [comment]
I've found the root of the problem. See googlei18n/noto-source#125

**Comment by Mystic-Mirage** [comment]
Fixed in noto-source. When we can expect a build with a fix?
I do not hurry you guys but there are a few months to the next Ubuntu LTS release and I really want this fix to be included.

**Comment by Vort** [comment]
It would be nice to see those characters fixed on osm.org.

**Comment by kmuncie** [comment]
@marekjez86 can you give some clarity on when the [fix merged into noto-source](https://github.com/googlefonts/noto-source/commit/7747a4a5088f660be233c61a0397ac94247e829b) will land in a build here? I just checked `noto-fonts/phaseIII_only/hinted/ttf/NotoSans/NotoSans-Regular.ttf` and I still see this bug present in that Version 2.003; ttfautohint (v1.8.2)

**Comment by moyogo** [comment]
The fix has been undone in the sources (https://github.com/googlefonts/noto-source/commit/57faa113d6c205ba2b60aeb26a193f7d150eed93) and the issue is still happening in 2.003.

**Comment by marekjez86** [comment]
this is a process problem: when Monotype fixes the issues or update Unicode source, they apply it to the source they have and not to the github sources. The only solution to this would be to stop relying on MT changing their sources. Is it possible to somehow remerge this (and I have other issues that were overwritten)?

**Comment by kmuncie** [comment]
@marekjez86 I apologize that I do not know much about the internal processes for how fixes make their way into source, so let me try and clarify it for myself.

This issue was fixed and merged in https://github.com/googlefonts/noto-source/pull/125 by a user submitted PR but then that work (and possibly many other fixes 🤷‍♂️ ) were overwritten by https://github.com/googlefonts/noto-source/pull/213 which appears to be an update from Monotype. 

It certainly does seem like a process problem if fixes are accepted here but never shared upstream to Monotype source. At the very least is it not possible to reconcile an update from Monotype with the current state of source in this repo so changes are not overwritten?

**Comment by nizarsq** [comment]
Quick test to see the status of this issue; apparently the 3 fonts NotoSans,NotoSerif and NotoSansMono are missing dots.
<img width="532" alt="Screen Shot 2020-07-14 at 12 16 39 AM" src="https://user-images.githubusercontent.com/22158882/87396175-4b121100-c567-11ea-9fdc-3142721e0936.png">

**Comment by visionario2** [comment]
I have checked the version of Noto Sans Regular in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSans and the problem is still occurring.

**Comment by exlevan** [comment]
What's the status of this issue? Can the fix be reapplied? Rendering of Ukrainian i has been broken for years by now.

**Comment by dpadar** [comment]
Ukrainian here. It is very strange, I would say disappointing, to see how these problem persist for years, while it's the only issue reported about Ukrainian. And it's even generic for all Cyrillic languages.

**Comment by rdaysky** [comment]
I re-created the PR and it got merged again: googlefonts/noto-source#279. Hopefully this fixes the issue.

@marekjez86, could you please check that googlefonts/noto-source#213 did not overwrite other fixes?

**Comment by marekjez86** [comment]
Updated all the fonts at https://github.com/googlefonts/noto-fonts 
@rdaysky : I'll check if there anything else messed up

**Comment by AleshaOleg** [comment]
Is fix works for somebody? Just got the latest version from https://www.google.com/get/noto/ and Ukrainian "і" still without a dot above.

**Comment by fitojb** [comment]
@AleshaOleg as a rule of thumb, fonts in this repository are newer than those in the marketing website.

**Comment by rdaysky** [comment]
@AleshaOleg https://github.com/googlefonts/noto-fonts contains fixed fonts

**Comment by AleshaOleg** [comment]
@fitojb @rdaysky thanks, guys! didn't expect that the latest [release](https://github.com/googlefonts/noto-fonts/releases/tag/v20201206-phase3) version is different from what's right now in the master branch. Now works as expected 👍

**Comment by kmuncie** [comment]
@marekjez86 the version of NotoSans-Regular.ttf still reports 2.003 - do fixes such as this go into a [release](https://github.com/googlefonts/noto-fonts/releases/tag/v20201206-phase3) with no bump to the version number of the font? 

Trying to keep my code base straight and have clear upgrades so any clarification of this is helpful. Thanks
