### ISSUE TITLE
Misplaced U+0FC6 TIBETAN SYMBOL PADMA GDAN

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1104]
### Font
NotoSansTibetan-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansTibetan-unhinted.zip
Date: 2018-03-21

### Font version
Version 1.01 uh

### Issue
U+0FC6 TIBETAN SYMBOL PADMA GDAN is positioned incorrectly. [The examples from the Tibetan and Himalayan Library](http://www.thlib.org/?wiki=/access/wiki/site/26a34146-33a6-48ce-001e-f16ce7908a6a/encoding%20model%20of%20the%20tibetan%20script%20in%20the%20ucs.html) indicate that it is centered below the preceding tsheg-bar or symbol, but I have not been able to find a full description; @eroux, do you know anything about this character?

### Character data
ཧྲཱིཿ࿆
U+0F67 TIBETAN LETTER HA
U+0FB2 TIBETAN SUBJOINED LETTER RA
U+0F71 TIBETAN VOWEL SIGN AA
U+0F72 TIBETAN VOWEL SIGN I
U+0F7F TIBETAN SIGN RNAM BCAD
U+0FC6 TIBETAN SYMBOL PADMA GDAN

### Screenshot
![ཧྲཱིཿ࿆](https://user-images.githubusercontent.com/1124347/37742270-53559330-2d3b-11e8-8c17-bdb769e10ec1.png)

**Comment by eroux** [comment]
I've asked around, Tibetans seems to consider it's only an illustration, not a character per se (I think it's just another of these oddities that shouldn't be in Unicode). It seems to never appear in texts, only in illustrations (thankas, rarely in illustrations in side boxes of manuscripts, etc.). I'll continue to look for examples in manuscripts, but noone I talked to has any idea so far...

It is not handled by the Monlam fonts (which are very widespread in Buddhist input projects that are the most likely to use this character). There are very few pre-composed combinations in the [PKTC fonts](http://www.pktc.org/pktc/SFTtypefaces.htm) and none in the DDC or MS Himalaya.

About character order I think you're right, but it's sort of hypothetical...

**Comment by marekjez86** [comment]
should be fixed in newly updated https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifTibetan (and its TTF counterpart)

**Comment by marekjez86** [comment]
[tib-1104-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/3288445/tib-1104-Serif.pdf)

**Comment by dscorbett** [comment]
This bug isn’t fixed. The rendering in that PDF looks the same as the image in my original comment.

**Comment by marekjez86** [comment]
corrected
[Prod-report_NotoSerifTibetan_857328.pdf](https://github.com/googlefonts/noto-fonts/files/8157207/Prod-report_NotoSerifTibetan_857328.pdf)
