### ISSUE TITLE
Tibetan marks affect kerning unnecessarily

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1344]
### Font
NotoSerifTibetan-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/b20c9c07139b22eb38013b1f80f9a5222c6058c6/phaseIII_only/unhinted/otf/NotoSerifTibetan/NotoSerifTibetan-Regular.otf
Date: 2018-10-12

### Font version
Version 2.000

### Issue
The kerning between some letters and tsheg is affected by intervening marks.

### Character data
ཥ་
U+0F65 TIBETAN LETTER SSA
U+0F0B TIBETAN MARK INTERSYLLABIC TSHEG
ཥཾ་
U+0F65 TIBETAN LETTER SSA
U+0F7E TIBETAN SIGN RJES SU NGA RO
U+0F0B TIBETAN MARK INTERSYLLABIC TSHEG

### Screenshot
![ཥ་ ཥཾ་](https://user-images.githubusercontent.com/1124347/47051744-85bcfe80-d173-11e8-979e-00cb98ccad7e.png)

**Comment by marekjez86** [comment]
should be fixed in newly updated https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifTibetan (and its TTF counterpart)

**Comment by marekjez86** [comment]
[tib-1344-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/3288464/tib-1344-Serif.pdf)

**Comment by dscorbett** [comment]
This bug is still present: it looks correct in the PDF, but the kerning is still inconsistent when I try it.
