### ISSUE TITLE
Noto Sans Tai Tham Issues 

### ISSUE THREAD

**Issue by Arloka** [googlefonts/noto-fonts#1749]
Font
NotoSansTaiTham-Regular.otf

Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/7a9a8dbf7c9193298a1b11ad2e9acf5e039fc530/phaseIII_only/unhinted/otf/NotoSansTaiTham/NotoSansTaiTham-Regular.otf
Date: 2020-05-014

Font version
Version 2.000

I have got Noto Sans Tai Tham (New version) form Marek. After doing a test I found some issues in the font. Here is the issues https://drive.google.com/open?id=1r63c0_1RuT2YBOYXvv-s_CPLuR9jkMV0 and This is the font used to explain it as a correct font https://drive.google.com/open?id=1Lusbn3C7C9blTLylJ2KCDCTS6CaVS6e5

**Comment by marekjez86** [comment]
I believe newly updated fonts in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansTaiTham fix the issues. Please advise, if not.

**Comment by Arloka** [comment]
Some of issues has been fixed in version 2.1. After doing a test I still found some issues. There are: 1) All consonant+uni1A55+uni1A6E uni1A6F uni1A70 uni1A71 uni1A72 not working.
![Screen Shot 2020-05-22 at 1 52 30 PM](https://user-images.githubusercontent.com/17794142/82653368-b82ab980-9c3c-11ea-975a-d7c4182875cc.png)
2) There is a problem about the sub of uni1A3F when used to type after uni1A36,uni1A3E+uni1A73,uni1A74+uni1A62,uni1A75+uni1A60+uni1A3F
![Screen Shot 2020-05-22 at 1 55 00 PM](https://user-images.githubusercontent.com/17794142/82653903-88c87c80-9c3d-11ea-9225-7ea8d9a7a950.png)
All of them should be like these: 
![Screen Shot 2020-05-22 at 3 06 59 PM](https://user-images.githubusercontent.com/17794142/82654207-fd9bb680-9c3d-11ea-8f67-08d57acba4cb.png)
3) These is a problem about uni1A7B. It is too high when typing without any upper vowel as:
![Screen Shot 2020-05-22 at 3 11 24 PM](https://user-images.githubusercontent.com/17794142/82654729-ce397980-9c3e-11ea-80ed-0470406c59c1.png)
It should be like this:
![Screen Shot 2020-05-22 at 3 10 49 PM](https://user-images.githubusercontent.com/17794142/82654789-e14c4980-9c3e-11ea-823c-35ddf40d4d60.png)
4) uni1A76 Its dot is a little bit small. It can not be seen in small sizes. Can you make it a little bit big. 
![Screen Shot 2020-05-22 at 3 22 35 PM](https://user-images.githubusercontent.com/17794142/82655648-1d33de80-9c40-11ea-991c-e2379d803ca2.png)

**Comment by nizarsq** [comment]
@Arloka can you open a bug for each issue remaining, also please add the exact text input or a sequence of unicode points for each issues. Thanks

**Comment by Arloka** [comment]
@nizarsq here the details of its issues what I found as i have mentioned above. This is a PDF file.https://drive.google.com/open?id=1d2qYuOnhgY6tneRfXh8GslE3vVclOuQ-
or see these
![Screen Shot 2020-05-26 at 10 59 49 AM](https://user-images.githubusercontent.com/17794142/82863881-df390200-9f40-11ea-8628-d4d2cc29f26f.png)

![Screen Shot 2020-05-26 at 10 59 03 AM](https://user-images.githubusercontent.com/17794142/82863868-d9dbb780-9f40-11ea-8bbb-30f4b20a93ae.png)
![Screen Shot 2020-05-26 at 10 59 28 AM](https://user-images.githubusercontent.com/17794142/82863875-dd6f3e80-9f40-11ea-90d4-110bd041acb2.png)
![Screen Shot 2020-05-26 at 10 59 40 AM](https://user-images.githubusercontent.com/17794142/82863876-de07d500-9f40-11ea-9d5f-cb9a6ca59cb0.png)

**Comment by nizarsq** [comment]
I created test case for th unicodes you mentioned in the PDF file, I can see the issue you mentioned. I used the font from this directory. Screenshot of the results I got attached.
<img width="832" alt="Screen Shot 2020-05-26 at 12 13 51 AM" src="https://user-images.githubusercontent.com/22158882/82871907-1bd80f80-9ee7-11ea-9e3c-9fe194328a38.png">

**Comment by Arloka** [comment]
Hi does it have any news about the fixing of Noto Sans Tai Tham?

**Comment by Arloka** [comment]
@nizarsq @marekjez86 Hi I don't hear about the news of Tai Tham Font for long. Aa present, how is its process? Thanks
