### ISSUE TITLE
Noto Looped Thai overwrites vowel-signs with tone marks

### ISSUE THREAD

**Issue by r12a** [googlefonts/noto-fonts#2005]
### Font 
NotoLoopedThai-Regular
Version 1.00; ttfautohint (v1.8.3) -l 8 -r 50 -G 200 -x 14 -D thai -f none -a qsq -X ""

### Where the font came from, and when
https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/NotoLoopedThai

### OS name and version
Mac OS X 11.2.1 Big Sur

### Application name and version
tested on Firefox and Chrome desktop browsers

### Issue
Tone marks overwrite superscript vowel-signs.

### Character data
ตี่นี้เอึ่งึ้ด้

### Screenshot
 ![Screenshot 2021-02-18 at 10 36 05](https://user-images.githubusercontent.com/4839211/108345089-cad71c80-71d5-11eb-8ab5-cc6877c6876d.png)

## Tools for reporting bugs
https://r12a.github.io/scripts/fontlist/?script=thai#result
you can show the sample text using the controls at the top of the page

**Comment by ProjectThreepio** [comment]
I'm seeing this as well, on Windows.

**Comment by stephankn** [comment]
I tried with the recent update 7a2f3e01677be1ce09e6ab9142cdbfefcb2bfb2b and still see the problem (Linux/Mapnik/Harfbuzz)

**Comment by davelab6** [comment]
Just found this in `ฉะนั้น บัดนี้`

<img width="1683" alt="Screen Shot 2021-08-23 at 1 56 10 PM" src="https://user-images.githubusercontent.com/261579/130494350-473ad130-009f-4638-aa05-8472bd835715.png">


@moyogo please can you determine if this was a recent regression, and if you can fix it, or if we need to get a thai specialist font engineer? :)

**Comment by marekjez86** [comment]
Should be fixed with the most recent release of the fonts

**Comment by suzuki11109** [comment]
![image](https://user-images.githubusercontent.com/4640086/157586255-f75daffe-959c-40bb-bbfc-2a9f10ecbf40.png)
I think the problem still exists with the latest font. Should we reopen this issue?

**Comment by simoncozens** [comment]
Actually, I'm convinced that this is fixed in the fonts we have available at https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoLoopedThai

The remaining problem is that the new version hasn't yet been onboarded to Google Fonts. I'm working on ways to make the onboarding process automatic on new releases, so rather than upgrade this one manually now, I'd prefer to get this new system finished off and then do all of them at once.

**Comment by yuuukun** [comment]
Checked and, Noto Loop Thai is definitely fixed. Interestingly, the one on Google fonts is Noto Sans Thai Looped though, is the name going to be changed there too? 

<img width="668" alt="image" src="https://user-images.githubusercontent.com/58155530/168262454-c3edbb7c-4d7c-428b-9d83-b23665f483de.png">
(Screenshort from Figma, the file you linked)

**Comment by simoncozens** [comment]
Noto Sans Thai Looped and Noto Looped Thai are the same font (although as mentioned the one on GF is an older version). I don't know why the names are different, but if it's on GF as "Noto Sans Thai Looped" it will almost certainly keep that name to avoid breaking everyone's web sites.

**Comment by ohbendy** [comment]
It was inadvertently renamed from the original "Noto Looped Thai" to "Noto Sans Looped Thai" (and the same for the Lao fonts). The longer name means the individual style names exceed the 31-character limit (it would be 'Noto Sans Thai Looped SmCd ExBd' for example). Such long names are invalid on Windows and the fonts won't install. So the names were reverted to the shorter we had originally, which were approved when we were working on the fonts.
