### ISSUE TITLE
Filenames causing problem with GitHub Desktop in Windows

### ISSUE THREAD

**Issue by DLasher106** [googlefonts/noto-fonts#2344]
The names of certain recently added files are invalid in Windows, which creates problems when pulling with GitHub Desktop.

The files are in the main/images/issue_data/ directory, a total of 8 files with names starting with “s:” (which is not valid in Windows filenames), such as `s: myanmar-TOP01-googlefonts.noto-fonts.weekly-data.csv`

**Comment by marekjez86** [comment]
@DLasher106 : should be fixed but please verify

**Comment by DLasher106** [comment]
**Not Fixed.**

It seems that the files with (invalid in Windows) names were _copied_ to files with valid names, but the invalid-name files are still there.

A fix requires _removing_ the files with “s:” in their names, so that they do not exist at all.

s:arabic-TOP03-googlefonts.noto-fonts.weekly-data-20220420.csv
s:arabic-TOP03-googlefonts.noto-fonts.weekly-data-20220425.csv
s:arabic-TOP03-googlefonts.noto-fonts.weekly-data-20220502.csv
s:latingreekcyrillic-TOP01-googlefonts.noto-fonts.weekly-data-20220420.csv
s:latingreekcyrillic-TOP01-googlefonts.noto-fonts.weekly-data-20220425.csv
s:latingreekcyrillic-TOP01-googlefonts.noto-fonts.weekly-data-20220502.csv
s:myanmar-TOP01-googlefonts.noto-fonts.weekly-data.csv
s:myanmar-TOP02-googlefonts.noto-fonts.weekly-data.csv
s:symbol-TOP02-googlefonts.noto-fonts.weekly-data-20220420.csv
s:tibetan-TOP03-googlefonts.noto-fonts.weekly-data-20220420.csv

**Comment by DLasher106** [comment]
**Fixed by the May 14 commit.**

Thanks!
