### ISSUE TITLE
Issues with displaying this "হ্যাঁ" character when using Noto sans bengali

### ISSUE THREAD

**Issue by marek-sedlak** [googlefonts/noto-fonts#2355]
## Defect Report
> Noto fonts can be obtained from https://github.com/googlefonts/noto-fonts/tree/master/unhinted/otf/ (unhinted OTF) or https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/ (hinted TTF). If you find a problem with either of these then please use this template to file a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
  > Issues with displaying this "হ্যাঁ" character when using Noto sans bengali

### Font 
  > Noto sans bengali

### Where the font came from, and when
  >   Site: https://fonts.google.com/noto/specimen/Noto+Sans
  >   Date: 2022-05-16 (preferred format)

### Font Version
  > * Win - but we are not sure if it's limited just to this platform

### OS name and version
  > Windows 10

### Application name and version
  > We can see the issues in most tools like INDD, Illustrator, word 
### Issue
  > When this character হ্যাঁ is used in text and Noto sans Bengali is picked as font family, it seems that the character is corrupted, I believe that the screenshot below shows the issue quite well. 

### Character data
  > Unfortunately not sure about the position of the font within the table

### Screenshot
![image](https://user-images.githubusercontent.com/105720011/168803692-a3cfa6aa-2bc6-4dc6-939f-bc1be5e67523.png)

**Comment by simoncozens** [comment]
This issue has been fixed in the latest version of Noto Sans Bengali:

![shape](https://user-images.githubusercontent.com/106728/168810225-9e53d95f-9b67-45ee-a3e3-c67974f3798e.png)

The fixed font can be downloaded from [here](https://github.com/googlefonts/noto-fonts/blob/main/hinted/ttf/NotoSansBengali/NotoSansBengali-Regular.ttf). However, that version is not currently available on Google Fonts. I'm working on a way to automatically bring new versions of Noto fonts to Google Fonts, but we're not quite there yet.

**Comment by marek-sedlak** [comment]
Hi Simon,
Well actually we were testing the new version and we can see that the Regular face type was corrected, however all other faces are still wrong, please take a look at the screenshot below.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/MAREK/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/MAREK/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/MAREK/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/MAREK/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=CS style='tab-interval:35.4pt;word-wrap:break-word'>




Only   regular type face seems to be updated, but others seems to be still wrong. | Only   regular is different, but probably not correct still. | We   have only regular updated, but other type faces seem to be working as well   now. I am not sure about the line below first character, was not there   before. | We   have only regular updated, but other typefaces seem to be working as well   now. I am not sure about the line below first character, was not there   before.
-- | -- | -- | --
  |   |   |  




</body>

</html>

**Comment by simoncozens** [comment]
Green (Adobe) is not doing any shaping at all - I suspect you need to turn on the "World Ready Composer" for Illustrator and/or turn on the [Harfbuzz Override](https://community.adobe.com/t5/indesign-discussions/script-for-enabling-harfbuzz-workflow-in-indesign/m-p/11295166) for InDesign.

I'll look at the other masters to see why the candrabindu positioning is different.

**Comment by marek-sedlak** [comment]
Hi Simon,
Thank you, we are testing your suggestions.
We will keep you posted

**Comment by marek-sedlak** [comment]
Hi Simon,
I would also like to ask, if it would be possible to combine the Language specific Noto sans variants as Benagli with the regular Noto sans. The reason why I am asking this is that we very often work with the text that is combination of Bengali or any other language specific font with latin characters.

**Comment by simoncozens** [comment]
When we move to the new build system, one of the outputs will be a "full" font with the script plus Noto Sans Latin. I'm hoping this will happen sometime in June.

**Comment by marek-sedlak** [comment]
Hi @simoncozens we have downloaded other masters as well. Please see the screenshot below: The red ones are still wrong
![image](https://user-images.githubusercontent.com/105720011/172309354-1fbf2311-f854-4209-9e0e-2383d9bb6158.png)

**Comment by marek-sedlak** [comment]
Hi @simoncozens,
Do you have any update on this one?

Thank you

Regards,

Marek S.

**Comment by simoncozens** [comment]
I think these must be caching issues with your software, or old versions of the fonts somewhere on your system. If all the weights are working in Figma, then there is no problem with the fonts we are supplying.

Note that on OS X, the font manager always uses system fonts in preference to user-supplied fonts of the same name. Since Noto Sans Bengali is a system font in OS X, it may well be picking up old versions from the operating system.
