### ISSUE TITLE
Problem with backticks

### ISSUE THREAD

**Issue by ile** [googlefonts/noto-fonts#736]
Hi,

I'm trying to type multiple successive backticks (backticks following each other, like in markdown `fence`) into a textarea, but it seems impossible: http://codepen.io/anon/pen/wWVxYo.

Is this a bug?

**Comment by TidharC** [comment]
Hi,


I tried entering text in backticks, e.g.:

```javascript
var s = "JavaScript syntax highlighting";
alert(s);
```
in both fields at the URL above, but don't see a problem (I used Chrome and Firefox on Mac OS).
Can you elaborate on the repro steps you are using?

**Comment by KatMomoi** [comment]
I can reproduce the problem at the page provided by ile.
The difference is that TidharC has local Noto (Sans/serif) fonts while I don't and so rely on the web font from Google.

Adding a few people who might be able to tell us why the difference.

**Comment by dougfelt** [comment]
Yes, I was thinking the same thing.  Our current copy of
hinted/NotoSans-Regular.ttf works fine with hb-view.  Perhaps someone on
the webfonts team should investigate.

**Comment by iverg** [comment]
It seems that 'grave' glyph class was changed from Mark to Base in recent versions of Noto. It is still 'Mark' in the webfont.

**Comment by KatMomoi** [comment]
David Kuettel, after looking at the current Noto Sans/Serif and comparing them to earlier versions, we believe that the web version you are delivering are older and  they behave as reported in this bug relative to U+0060.  Do you plan to update the web version soon?

**Comment by aiwebb** [comment]
FYI, this issue has been referenced in today's HN post about the project:

https://news.ycombinator.com/item?id=12655054

**Comment by xiangyexiao** [comment]
I saw the comment in hacker news too. I have passed the comments to Google Fonts team and will get it fixed.

**Comment by seeschloss** [comment]
For what it's worth, I have the same problems with the following characters in addition to grave accent:

    ¨ (U+00A8 DIAERESIS)
    ´ (U+00B4 ACUTE ACCENT)
    ¸ (U+00B8 CEDILLA)

The other dead keys I know about (and have on my keyboard) work as expected though, like ^, ~ or °

**Comment by caub** [comment]
Yes, there's a problem with backticks: https://jsbin.com/qizoxoc/edit?html,css,output

**Comment by rabid-hatter** [comment]
I am experiencing this issue with the grave accent taking no width in Firefox (I'm running v50 and v52) in both Windows and Linux when noto sans is not installed locally. IE 11 works fine regardless of whether the font is installed locally or is pulling from Google.

**Comment by jolitinh** [comment]
Are there any plans on fixing this?

**Comment by davelab6** [comment]
Yes this will be fixed soon.

**Comment by jvacek** [comment]
Sorry, are there any updates?

**Comment by marekjez86** [comment]
@jvacek : have you tried, this should have been fixed about a month or two ago

**Comment by kirillku** [comment]
@marekjez86, It's still broken.
![image](https://user-images.githubusercontent.com/3331461/37959942-fffbed5c-31bc-11e8-9ff5-7ce7a88837dc.png)

**Comment by kvolkovich-sc** [comment]
Any updates?

**Comment by rewhowe** [comment]
I'm not sure if this helps or is related at all, but I've noticed this bug has started happening recently to another font, [Ricty Diminished](https://www.rs.tus.ac.jp/yyusa/ricty_diminished.html).

Coincidentally, I've also updated to the latest Chrome recently (Version 72.0.3626.121 (Official Build) (64-bit)). Whether this is the cause or not, I'm unsure.

I've confirmed the bug happens on Fire Fox version 64.0.2 (64-bit) as well, but *does not* happen on Opera version 58.0.3135.79.

With respect to Noto Sans, the bug appears on all three browsers...

**Comment by dylemma** [comment]
Bumping this since it's been over a year since "this should have been fixed about a month or two ago".

**Comment by marekjez86** [comment]
Unable to reproduce "I'm trying to type multiple successive backticks (backticks following each other, like in markdown fence) into a textarea, but it seems impossible: http://codepen.io/anon/pen/wWVxYo."

**Comment by natewiebe13** [comment]
@marekjez86 I'm able to reproduce on Ubuntu 18.04 on both Firefox and Chrome. This could be also related to the OS, not just the browser.

**Comment by marekjez86** [comment]
I reopened the issue but IMHO this is not the font issue (or at least not in the version that I have)

**Comment by marekjez86** [comment]
Firefox Quantum 67.0 (64-bit) on MacOS 10.14.5 (18F132) also looks/behaves fine:

<img width="1545" alt="Screen Shot 2019-06-13 at 12 33 48" src="https://user-images.githubusercontent.com/13322623/59462081-b8d59180-8dd7-11e9-960d-b4bd711f8d90.png">

**Comment by dohliam** [comment]
This issue still occurs in Firefox 67.0.1 on Ubuntu 18.04.1:

![image](https://user-images.githubusercontent.com/9295750/59464825-52a03d00-8dde-11e9-8538-0214929fb2b6.png)

Chromium 74.0.3729.169 on the same system is fine though:

![image](https://user-images.githubusercontent.com/9295750/59464889-7b283700-8dde-11e9-8d2b-60c1cad43af8.png)

**Comment by nanaya** [comment]
Still having problem on Firefox 67.0.2 and Chrome 75.0.3770.90 on Windows 8.1.

**Comment by dylemma** [comment]
Interestingly, I do *not* get this problem with the Edge browser. Chrome (75.0.3770.90) and Firefox (65.0.2) do. (I'm on Windows 10, version 1803 fwiw).

**Comment by dylemma** [comment]
https://github.com/chrismsimpson/Metropolis/issues/15 looks like a similar issue. Looks like they haven't figured out what's going wrong either :(

**Comment by nanaya** [comment]
Those not having this problem may want to make sure it's not using installed system font which apparently is fine.

**Comment by apdrsn** [comment]
Will this be fixed, or should we look for another font?

**Comment by KenProle** [comment]
@davelab6 are there any plans to fix this?

**Comment by tjcrowder** [comment]
This has been driving me nuts on Twitter since their UI update. I finally tracked it down to Noto Sans, which is only used when you're logged in (and only on my Linux OS version of Chrome/Brave, not Windows versions). It's being triggered by a style rule in the Twitter UI setting `system-ui` as the font for tweets, and on my system, that triggers Noto Sans (whereas `sans-serif` triggers Liberation Sans, which doesn't have this problem).

**Comment by kizu** [comment]
A workaround: with the powers of CSS we can substitute the backtick with any other font — https://codepen.io/kizu/pen/MWaqOBX

**Comment by roelvanduijnhoven** [comment]
Not sure if this helps, but I encounter this problem in Ubuntu 20.04 as well. Backticks will be laid on top each other.

**Comment by matkot** [comment]
For anyone that still encounters this problem:

Issue seems to be present in fonts hosted by Google (downloaded from https://fonts.google.com/specimen/Noto+Sans) but it's fixed in newer versions.

`fc-query -f '%{fontversion}\n'` on font file (NotoSans-Regular.ttf) returns:
- `68157` on font file served by Google;
- `131334` on the font file from github (as of today)

Here results while using file version `68157`:
![image](https://user-images.githubusercontent.com/8456316/106110917-a5617080-614b-11eb-9a5e-4da6b70e307a.png)

And file version `131334`:
![image](https://user-images.githubusercontent.com/8456316/106110955-b316f600-614b-11eb-9101-4aba1b570d97.png)

**Comment by simoncozens** [comment]
This now seems to be fixed:
<img width="485" alt="Screenshot 2022-06-27 at 11 05 32" src="https://user-images.githubusercontent.com/106728/175917077-0981c113-ce30-4255-93bf-47e17dfe38da.png">
